name: Node Build en test

on:
  push:
      branches: [main]

jobs:
  test_pull_request:
    runs-on: ${{matrix.os}}
    
    strategy:
     matrix:
      node-versions: [16.x]
      os: [ubuntu-latest, windows-latest]
      
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{matrix.node-versions}}
        uses: actions/setup-node@v1
        with:
          node-versions: ${{matrix.node-versions}}
      - run: npm ci //clean install
      - run: npm test
      - run: npm run build
